[package]
name = "image-data"
version = "0.0.0"
edition = "2024"

[profile.release]
opt-level = 'z'

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
image = { version = "0.25.9", features = ["default"]}
wasm-bindgen = "0.2.109"